### ISSUE TITLE
License suggestion

### ISSUE THREAD

**Issue by mediafinger** [terrainoob/cave_lords#4]
Hey, nice project!

I've seen you are looking for a license which allows others to use your code for learning, without selling it - or offering the resulting game as service. Maybe the [Redis Source Available License (RSALv2)](https://redis.com/legal/rsalv2-agreement/) would be fitting for this project.

**Comment by terrainoob** [comment]
Thanks @mediafinger! On the surface, it looks like the perfect thing.  I'll dig into it and make sure it doesn't violate any of my wants, but I'm thinking you're correct here!

**Comment by terrainoob** [comment]
Added to the repo.  Thanks!
